// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/domain.proto

/*
Package domain is a generated protocol buffer package.

It is generated from these files:
	domain/domain.proto

It has these top-level messages:
	LineItem
	ItemAdded
	ItemRemoved
	Cart
*/
package domain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LineItem struct {
	ProductId string `protobuf:"bytes,1,opt,name=productId" json:"productId,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Quantity  int32  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *LineItem) Reset()                    { *m = LineItem{} }
func (m *LineItem) String() string            { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()               {}
func (*LineItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LineItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *LineItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LineItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

// The item added event.
type ItemAdded struct {
	Item *LineItem `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *ItemAdded) Reset()                    { *m = ItemAdded{} }
func (m *ItemAdded) String() string            { return proto.CompactTextString(m) }
func (*ItemAdded) ProtoMessage()               {}
func (*ItemAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ItemAdded) GetItem() *LineItem {
	if m != nil {
		return m.Item
	}
	return nil
}

// The item removed event.
type ItemRemoved struct {
	ProductId string `protobuf:"bytes,1,opt,name=productId" json:"productId,omitempty"`
}

func (m *ItemRemoved) Reset()                    { *m = ItemRemoved{} }
func (m *ItemRemoved) String() string            { return proto.CompactTextString(m) }
func (*ItemRemoved) ProtoMessage()               {}
func (*ItemRemoved) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ItemRemoved) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

// The shopping cart state.
type Cart struct {
	Items []*LineItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *Cart) Reset()                    { *m = Cart{} }
func (m *Cart) String() string            { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()               {}
func (*Cart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Cart) GetItems() []*LineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*LineItem)(nil), "com.example.shoppingcart.persistence.LineItem")
	proto.RegisterType((*ItemAdded)(nil), "com.example.shoppingcart.persistence.ItemAdded")
	proto.RegisterType((*ItemRemoved)(nil), "com.example.shoppingcart.persistence.ItemRemoved")
	proto.RegisterType((*Cart)(nil), "com.example.shoppingcart.persistence.Cart")
}

func init() { proto.RegisterFile("domain/domain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x89, 0xdd, 0x4a, 0x77, 0x0a, 0x22, 0xf1, 0x12, 0xc4, 0xc3, 0x12, 0x3c, 0x14, 0x84,
	0x08, 0xfa, 0x09, 0xac, 0x5e, 0x0a, 0x05, 0x61, 0x4f, 0xe2, 0x2d, 0x26, 0x83, 0x06, 0xcc, 0x1f,
	0x93, 0xa9, 0xe8, 0xb7, 0x97, 0xcd, 0xae, 0x7a, 0x13, 0xe9, 0x29, 0x79, 0x33, 0xfc, 0xde, 0x3c,
	0x1e, 0x9c, 0xd8, 0xe8, 0xb5, 0x0b, 0x97, 0xe3, 0xa3, 0x52, 0x8e, 0x14, 0xf9, 0xb9, 0x89, 0x5e,
	0xe1, 0x87, 0xf6, 0xe9, 0x15, 0x55, 0x79, 0x89, 0x29, 0xb9, 0xf0, 0x6c, 0x74, 0x26, 0x95, 0x30,
	0x17, 0x57, 0x08, 0x83, 0x41, 0xf9, 0x00, 0x8b, 0xad, 0x0b, 0xb8, 0x21, 0xf4, 0xfc, 0x0c, 0xda,
	0x94, 0xa3, 0xdd, 0x19, 0xda, 0x58, 0xc1, 0x3a, 0xb6, 0x6a, 0xfb, 0xdf, 0x01, 0xe7, 0xd0, 0x04,
	0xed, 0x51, 0x1c, 0xd4, 0x45, 0xfd, 0xf3, 0x53, 0x58, 0xbc, 0xed, 0x74, 0x20, 0x47, 0x9f, 0x62,
	0xd6, 0xb1, 0xd5, 0xbc, 0xff, 0xd1, 0xf2, 0x1e, 0xda, 0xc1, 0xf5, 0xc6, 0x5a, 0xb4, 0x7c, 0x0d,
	0x8d, 0x23, 0xf4, 0xd5, 0x75, 0x79, 0xa5, 0xd4, 0x7f, 0xb2, 0xa9, 0xef, 0x60, 0x7d, 0x65, 0xe5,
	0x05, 0x2c, 0xab, 0x42, 0x1f, 0xdf, 0xd1, 0xfe, 0x9d, 0x56, 0x6e, 0xa1, 0xb9, 0xd5, 0x99, 0xf8,
	0x1d, 0xcc, 0x07, 0xb8, 0x08, 0xd6, 0xcd, 0xf6, 0xb8, 0x3c, 0xc2, 0xeb, 0xe3, 0xc7, 0xa3, 0x89,
	0x99, 0x3a, 0x7e, 0x3a, 0xac, 0x25, 0x5f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x13, 0xbd,
	0xae, 0x7b, 0x01, 0x00, 0x00,
}
