apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:
  datastore:
    name: my-postgres-store
  containers:
    - image: shoppingcart:local-2
      env:
      - name: HOST
        value: localhost
---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: my-postgres-store
spec:
  type: Postgres
  deployment: Unmanaged
  config:
    service: postgresql.cart.svc.cluster.local
    credentials:
      database: postgres
      username: postgres
      password: mntb8PVk0K